# Generated by Django 4.2.19 on 2025-03-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=200)),
                ('text', models.TextField(default='<#a>1<a#><#t>Title<t#><#d>Description<d#><#id><id#>')),
                ('repa', models.TextField(default='[1]')),
            ],
        ),
    ]
