# Generated by Django 4.2.19 on 2025-03-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camdata',
            old_name='text',
            new_name='data',
        ),
    ]
