# Generated by Django 4.2.19 on 2025-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsc', '0002_rename_text_camdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='camdata',
            name='cam_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
