# Generated by Django 4.2.19 on 2025-03-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsc', '0003_camdata_cam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camdata',
            name='cam_id',
        ),
    ]
