# Generated by Django 4.2.19 on 2025-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsc', '0004_remove_camdata_cam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camdata',
            name='repa',
        ),
        migrations.AddField(
            model_name='camdata',
            name='unit',
            field=models.TextField(default='€'),
        ),
    ]
