# Generated by Django 4.2.19 on 2025-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsc', '0005_remove_camdata_repa_camdata_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camdata',
            name='unit',
            field=models.TextField(default='€', max_length=20),
        ),
    ]
