# Generated by Django 4.2.19 on 2025-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsc', '0006_alter_camdata_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='camdata',
            name='sources',
            field=models.TextField(default=''),
        ),
    ]
