# Generated by Django 4.2.6 on 2024-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mapdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("map_data", models.TextField()),
                ("map_path", models.TextField()),
            ],
        ),
    ]
