# Generated by Django 5.1.4 on 2024-12-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mindmap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapdata",
            name="map_link",
            field=models.TextField(default="{}"),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="map_data",
            field=models.TextField(default="{}"),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="map_path",
            field=models.TextField(default="{}"),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="owner",
            field=models.CharField(default="Anonymous", max_length=200),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="title",
            field=models.CharField(default="Untitled", max_length=200),
        ),
    ]
