# Generated by Django 5.1.4 on 2024-12-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mindmap", "0002_mapdata_map_link_alter_mapdata_map_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapdata",
            name="map_data",
            field=models.TextField(default=" "),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="map_link",
            field=models.TextField(default=" "),
        ),
        migrations.AlterField(
            model_name="mapdata",
            name="map_path",
            field=models.TextField(default=" "),
        ),
    ]
