# Generated by Django 4.2.19 on 2025-02-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0006_alter_mapdata_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='map_data',
            field=models.TextField(default='<#i>1<i#><#t>Start node<t#>'),
        ),
    ]
