# Generated by Django 4.2.19 on 2025-03-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0007_alter_mapdata_map_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdata',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
